extends Node

var buttons_work:=true
var which_boar_item:=0
var please:=true
var doneb:=true
var bdead:=false
var whichb:=0
var tusk:=0
var trackT:=0
var hoof:=0
var trackH:=0
var rand_tusk:=0
var rand_hooves:=0
var fightb:=false
var collectTPerm:=false
var collectT:=false
var collectHPerm:=false
var bvisible:=false
