extends Node

var buttons_work:=true
var which_boar_item:=0
var please:=true
var doneb:=true
var bdead:=false
var whichb:=0
var tusk:=10
var trackT:=10
var hoof:=10
var trackH:=10
var rand_tusk:=0
var rand_hooves:=0
var fightb:=false
var collectTPerm:=true
var collectT:=false
var collectHPerm:=true
var bvisible:=false
